version: "3.7"

services:
  db:
    image: "postgres:12.2-alpine"
    container_name: "tes-db"
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ".env"

  api:
    build: "./"
    ports:
      - "${EXPRESS_PORT}:3000"
    env_file:
      - ".env"
  